DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS managers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS foods CASCADE;
